channels:
- pytorch
- nvidia
- defaults
- conda-forge
dependencies:
- python=3.10.16
- pip=24.2
- numpy=1.26.4
- einops=0.8.0
- jaxtyping=0.2.34
- jupyter=1.0.0
- plotly=5.24.1
- pytorch=2.5.1
- pytorch-cuda=12.4
- safetensors=0.4.5
- scikit-learn=1.5.2
- torchaudio=2.5.1
- torchvision=0.20.1
- pip:
  - arrow==1.3.0
  - captum==0.7.0
  - chardet==4.0.0
  - cloudpickle==3.1.0
  - eagerpy==0.30.0
  - eval-type-backport==0.2.2
  - foolbox==3.3.4
  - fqdn==1.5.1
  - gdown==5.2.0
  - grad-cam==1.5.4
  - idna==2.10
  - imageio==2.36.0
  - isoduration==20.11.0
  - jsonpatch==1.33
  - jsonpointer==3.0.0
  - jupyter-server-mathjax==0.2.6
  - lazy-loader==0.4
  - lime==0.2.0.1
  - nbdime==4.0.2
  - opencv-python==4.10.0.84
  - remote-plot==1.2.1
  - requests==2.25.1
  - scikit-image==0.24.0
  - shap==0.46.0
  - slicer==0.0.8
  - sympy==1.13.1
  - tifffile==2024.8.30
  - torch-kmeans==0.2.0
  - torchattacks==3.5.1
  - torcheval==0.0.7
  - ttach==0.0.3
  - types-python-dateutil==2.9.0.20241003
  - uri-template==1.3.0
  - urllib3==1.26.20
  - wandb==0.19.8
  - webcolors==24.11.1
  - git+https://github.com/microsoft/torchgeo.git@91d8272
