channels:
- pytorch
- nvidia
- defaults
- conda-forge
dependencies:
- einops=0.8.0
- jaxtyping=0.2.34
- jupyter=1.0.0
- pytorch=2.5.1
- safetensors=0.4.5
- scikit-learn=1.5.2
- torchaudio=2.5.1
- torchgeo=0.5.2
- torchvision=0.20.1
- wandb=0.18.5
- pip:
  - arrow==1.3.0
  - captum==0.7.0
  - cloudpickle==3.1.0
  - fqdn==1.5.1
  - gdown==5.2.0
  - imageio==2.36.0
  - isoduration==20.11.0
  - jsonpointer==3.0.0
  - jupyter-server-mathjax==0.2.6
  - lazy-loader==0.4
  - lime==0.2.0.1
  - llvmlite==0.43.0
  - nbdime==4.0.2
  - numba==0.60.0
  - scikit-image==0.24.0
  - shap==0.46.0
  - slicer==0.0.8
  - sympy==1.13.1
  - tifffile==2024.8.30
  - torcheval==0.0.7
  - types-python-dateutil==2.9.0.20241003
  - uri-template==1.3.0
  - webcolors==24.11.1
