channels:
- pytorch
- nvidia
- defaults
- conda-forge
dependencies:
- python=3.10.16
- pip=24.2
# pin pre-version 2 numpy to use e.g. np.trapz
- numpy=1.26.4
- einops=0.8.0
- jaxtyping=0.2.34
- jupyter=1.0.0
- plotly=5.24.1
- pytorch=2.5.1
# comment out pytorch-cuda below for macOS installs
- pytorch-cuda=12.4
- safetensors=0.4.5
- scikit-learn=1.5.2
- torchaudio=2.5.1
- torchvision=0.20.1
- pytables=3.10.1
- pip:
  - aenum==3.1.15
  - affine==2.4.0
  - aiohappyeyeballs==2.6.1
  - aiohttp==3.11.14
  - aiosignal==1.3.2
  - annotated-types==0.7.0
  - antlr4-python3-runtime==4.9.3
  - arrow==1.3.0
  - async-timeout==5.0.1
  - bitsandbytes==0.45.3
  - captum==0.7.0
  - chardet==4.0.0
  - click==8.1.8
  - click-plugins==1.1.1
  - cligj==0.7.2
  - cloudpickle==3.1.0
  - colorama==0.4.6
  - contourpy==1.3.1
  - cycler==0.12.1
  - dill==0.3.9
  - docker-pycreds==0.4.0
  - docstring-parser==0.16
  - eagerpy==0.30.0
  - efficientnet-pytorch==0.7.1
  - eval-type-backport==0.2.2
  - fiona==1.10.1
  - fonttools==4.56.0
  - foolbox==3.3.4
  - fqdn==1.5.1
  - frozenlist==1.5.0
  - fsspec==2025.3.0
  - gdown==5.2.0
  - gitdb==4.0.12
  - gitpython==3.1.44
  - grad-cam==1.5.4
  - huggingface-hub==0.29.3
  - hydra-core==1.3.2
  - idna==2.10
  - imageio==2.36.0
  - importlib-resources==6.5.2
  - isoduration==20.11.0
  - jsonargparse==4.37.0
  - jsonpatch==1.33
  - jsonpointer==3.0.0
  - jupyter-server-mathjax==0.2.6
  - kiwisolver==1.4.8
  - kornia==0.8.0
  - kornia-rs==0.1.8
  - lazy-loader==0.4
  - lightly==1.5.19
  - lightly-utils==0.0.2
  - lightning==2.5.0.post0
  - lightning-utilities==0.14.1
  - lime==0.2.0.1
  - llvmlite==0.44.0
  - markdown-it-py==3.0.0
  - matplotlib==3.10.1
  - mdurl==0.1.2
  - multidict==6.2.0
  - multiprocess==0.70.17
  - munch==4.0.0
  - nbdime==4.0.2
  - numba==0.61.0
  - omegaconf==2.3.0
  - opencv-python==4.10.0.84
  - pandas==2.2.3
  - pretrainedmodels==0.7.4
  - propcache==0.3.0
  - protobuf==5.29.3
  - pyarrow==19.0.1
  - pydantic==2.10.6
  - pydantic-core==2.27.2
  - pyparsing==3.2.1
  - pyproj==3.7.1
  - pytorch-lightning==2.5.0.post0
  - pytz==2025.1
  - rasterio==1.4.3
  - remote-plot==1.2.1
  - requests==2.25.1
  - rich==13.9.4
  - rtree==1.4.0
  - scikit-image==0.24.0
  - segmentation-models-pytorch==0.4.0
  - sentry-sdk==2.23.1
  - setproctitle==1.3.5
  - shap==0.46.0
  - shapely==2.0.7
  - slicer==0.0.8
  - smmap==5.0.2
  - sympy==1.13.1
  - tensorboardx==2.6.2.2
  - tifffile==2024.8.30
  - timm==1.0.15
  - torch-kmeans==0.2.0
  - torchattacks==3.5.1
  - torcheval==0.0.7
# we need torchgeo v0.7.0 development version (has reBEN)
  - git+https://github.com/microsoft/torchgeo.git@91d8272
  - torchmetrics==1.6.3
  - tqdm==4.67.1
  - ttach==0.0.3
  - types-python-dateutil==2.9.0.20241003
  - typeshed-client==2.7.0
  - tzdata==2025.1
  - uri-template==1.3.0
  - urllib3==1.26.20
  - wandb==0.19.8
  - webcolors==24.11.1
  - xlsxwriter==3.2.2
  - yarl==1.18.3
